### ISSUE TITLE
Vignette Templates

### ISSUE THREAD

**Issue by freezenik** [gamlss-dev/gamlss2#6]
I just added vignette templates in the [gamlss2/vignettes](https://github.com/gamlss-dev/gamlss2/tree/main/vignettes) folder. I have several topics, which I thought could be assigned to:

* [random.Rmd](https://github.com/gamlss-dev/gamlss2/blob/main/vignettes/random.Rmd), @gillheller + @rigbyr 
* [spatial.Rmd](https://github.com/gamlss-dev/gamlss2/blob/main/vignettes/spatial.Rmd), @tkneib + @freezenik 
* [s+pb.Rmd](https://github.com/gamlss-dev/gamlss2/blob/main/vignettes/s%2Bpb.Rmd), @mstasinopoulos 
* [topmodels.Rmd](https://github.com/gamlss-dev/gamlss2/blob/main/vignettes/topmodels.Rmd), @zeileis 
* [selection](https://github.com/gamlss-dev/gamlss2/blob/main/vignettes/selection.Rmd), @mstasinopoulos + @freezenik 
* [families.Rmd](https://github.com/gamlss-dev/gamlss2/blob/main/vignettes/families.Rmd), @freezenik 

If you have other topics in mind, please post them here. I put all vignettes in [.Rbuildignore](https://github.com/gamlss-dev/gamlss2/blob/main/.Rbuildignore) for the moment and at them when they are ready. All vignettes are then shown on the website [https://gamlss-dev.github.io/gamlss2/](https://gamlss-dev.github.io/gamlss2/).

**Comment by mstasinopoulos** [comment]
Dear Niki and All


Thanks for your templates 

i) For me it will be easier to make them in quarto. 
   This  because  I use quarto for a year  and I think I have solved most of the problem associated with it.

ii) I try to recompile gamlss2 with the vignettes but It give an error

 * creating vignettes ... ERROR
--- re-building ‘gamlss2.Rmd’ using rmarkdown
--- finished re-building ‘gamlss2.Rmd’

--- re-building ‘random.Rmd’ using rmarkdown
--- finished re-building ‘random.Rmd’

--- re-building ‘s+pb.Rmd’ using rmarkdown
Error: processing vignette 's+pb.Rmd' failed with diagnostics:
Failed to locate ‘weave’ output file ‘s+pb.pdf’ or ‘s+pb.html’ for vignette with name ‘s+pb’ and engine ‘knitr::rmarkdown’. The following files exist in working directory ‘/private/var/folders/2s/77r_lrjx2ll5jv1ykl58dw_40000gn/T/RtmpD8TKYK/Rbuildcc4440b71c1b/gamlss2/vignettes’: ‘families.Rmd’ (552 bytes), ‘gamlss2.R’ (476 bytes), ‘gamlss2.Rmd’ (2318 bytes), ‘gamlss2.bib’ (1059 bytes), ‘gamlss2.html’ (1.49725e+06 bytes), ‘random.R’ (101 bytes), ‘random.Rmd’ (545 bytes), ‘random.html’ (1.24618e+06 bytes), ‘s+pb.R’ (101 bytes), ‘s+pb.Rmd’ (606 bytes), ‘s+pb.html’ (1.24628e+06 bytes), ‘selection.Rmd’ (603 bytes), ‘spatial.Rmd’ (549 bytes), ‘topmodels.Rmd’ (556 bytes)
--- failed re-building ‘s+pb.Rmd’

Any clue why? It looks the problem is s+pb (I wander if it is the + in the name)

iiI) How big the vignette should be? Up to 5-6 pages maybe? Or can be more detailed? 
   My feeling is that it should be small with other extra documentation in the web cite.

Thanks

Mikis

**Comment by mstasinopoulos** [comment]
In connection with the name of the vignette 

I rename thefile `s_pb.Rmd` and seems to compiled

Thanks

Mikis

**Comment by zeileis** [comment]
If we want to do qmd instead of Rmd we can easily re-name the files. Then, instead of the `output:` in the YAML, we should use `format:`. For example:

```
format: 
  html:
    html-math-method: mathjax
    toc: true
    number-sections: true
```

The result in the altdoc page will look very similar.

In principle, it's also possible and mix the vignettes and have some in Rmd and some in qmd. But, if possible, it's eaiser if we are consistent.

**Comment by mstasinopoulos** [comment]
Thanks

 Achim for showing how to  transfer to quarto 

Here is my modify .qmd  version if one wands to compere it with the original  .Rmd  one.


Thanks

Mikis


￼
